---
main_config:
  step: generate-profiles
  pipeline: Pooled Cell Painting
  project_tag: 2018_11_20_Periscope_Calico
---
core:
  batch: 20190919_6W_CP074A
  project_dir: /Users/gway/work/projects/
  site_dir: ../0.preprocess-sites/data/
  output_single_cell_dir: single_cell/
  output_profile_dir: profiles/
  output_one_single_cell_file_only: false
  categorize_cell_quality: simple
  compression: gzip
  float_format: "%.5g"
  compartments:
    - Cells
    - Nuclei
    - Cytoplasm
  parent_cols:
    cells:
      - Parent_Nuclei
    cytoplasm:
      - Parent_Nuclei
      - Parent_Cells
    spots:
      - Parent_Cells
  id_cols:
    - ImageNumber
    - ObjectNumber
  control_barcodes:
    - NT
  ignore_files:
    - .DS_Store
---
single_cell:
  perform: true
  force_overwrite: false
  prefilter_features: true
  filter_cell_quality:
    - Perfect
    - Great
  cell_quality_column: Metadata_Foci_Cell_Quality
  output_basedir: data/single_cell
  merge_columns:
    image_column: ImageNumber
    linking_compartment: Cytoplasm
    linking_columns:
      cells: Metadata_Cytoplasm_Parent_Cells
      nuclei: Metadata_Cytoplasm_Parent_Nuclei
    metadata_linking_columns:
      - Metadata_Foci_site
      - Metadata_Cells_ObjectNumber
---
aggregate:
  perform: true
  output_basedir: data/profiles
  operation: median
  features: infer
  levels:
    gene:
      - Metadata_Foci_Barcode_MatchedTo_GeneCode
    guide:
      - Metadata_Foci_Barcode_MatchedTo_GeneCode
      - Metadata_Foci_Barcode_MatchedTo_Barcode
---
normalize:
  perform: true
  output_basedir: data/profiles
  method: standardize
  levels:
    - gene
    - guide
    - single_cell
  by_samples: all
  features: infer
---
feature_select:
  perform: true
  output_basedir: data/profiles
  operations:
    - variance_threshold
    - drop_na_columns
    - blacklist
    - drop_outliers
  levels:
    - gene
    - guide
    - single_cell
  drop_samples: none
  features: infer
  na_cutoff: 0
  corr_threshold: 0.9
